name: Thanks-Diary CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Clean and Build JAR
        run: ./gradlew clean build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_NAME }}:${{ secrets.IMAGE_TAG }} .
          docker push ${{ secrets.ECR_REPOSITORY_NAME }}:${{ secrets.IMAGE_TAG }}

      - name: Remove local Docker images
        run: docker image prune -af

  deploy:
    name: Deploy to Server
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2 instance
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_EC2_IP_DEV }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

            export IMAGE_NAME="${{ secrets.IMAGE_NAME }}"
            export IMAGE_STORAGE="${{ secrets.ECR_REPOSITORY }}"
            export BUILD_NUMBER="${{ secrets.IMAGE_TAG }}"
            
            /home/ubuntu/thanks-diary-dev/deploy.sh
            
            echo "Checking service health..."
            curl -f http://localhost:8080/health || { echo "Health check failed"; exit 1; }
